{{- if .Values.jaeger.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-account
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one
{{- end }}
